language: php
php:
  - "8.2"
  - "8.1"
  - "8.0"

before_script:
  - mkdir -p build/logs
  - composer install


script: phpunit --verbose --coverage-clover build/logs/clover.xml --configuration tests/phpunit.xml

after_script:
  - php vendor/bin/coveralls -v

notifications:
  email:
    recipients:
      - idinu@techlang.ro
    on_success: change
    on_failure: always
