language: php
php:
  - "5.5"
  - "5.4"
  - "5.3"

before_script:
  - composer install

script: phpunit --configuration tests/phpunit.xml

notifications:
  email:
    recipients:
      - idinu@techlang.ro
    on_success: change
    on_failure: always
